GET http://localhost:3000/categories/10/20
###
GET  http://localhost:3000/categories/120
###
POST  http://localhost:3000/categories
###
PATCH  http://localhost:3000/categories
###
DELETE  http://localhost:3000/categories/120